from typing import Any, Dict, Tuple, Union

REDIS_CLIENT_TEMP_TYPE = Any
WEBSOCKET_TEMP_TYPE = Any

FLASK_ROUTE_RESPONSE_VAL = Union[str, Dict[Any, Any]]
FLASK_ROUTE_RESPONSE_CODE = int


FLASK_RESPONSE_TYPE = Union[FLASK_ROUTE_RESPONSE_VAL, Tuple[FLASK_ROUTE_RESPONSE_VAL, FLASK_ROUTE_RESPONSE_CODE]]
